### ISSUE TITLE
Mise à disposition de l'identité ProConnect

### ISSUE THREAD

**Issue by 7studio** [GouvernementFR/dsfr#1107]
Bonjour,

j'ai bien conscience que le DSFR est avant tout destiné aux sites publics mais comme celui-ci est aussi poussé pour des applications d'agents de l'état, il me semblerait légitime de faciliter son utilisation en embarquant l'identité [ProConnect](https://www.proconnect.gouv.fr/). 

Cette nouvelle identité pourrait être mise à disposition dans le composant "Bouton FranceConnect" qui avait déjà anticiper son possible renommage avec sa classe HTML générique `fr-connect` :bowtie:

En cherchant un peu, j'ai trouvé deux projets qui avait déjà surchargé le composant du DSFR pour gérer ce cas :
* [MonAideCyber](https://monaide.cyber.gouv.fr/connexion).
* [AudioConf](https://audioconf.numerique.gouv.fr/)

et ils ne doivent pas être les seuls.

Pour la mise en pratique, l'ajout d'un nouveau modificateur suffirait : `fr-connect--pro`. Comme c'est déjà le cas pour gérer la version FranceConnect+.

J'espère que cette évolution sera bien accueillie :blush:

**Comment by AntoineGirard** [comment]
Bonjour,

Côté RDV Service Public nous avons fait de même également : https://github.com/betagouv/rdv-service-public/blob/production/app/javascript/stylesheets/vendor/proconnect_button_dsfr.scss

L’intégration native dans le DSFR serait un + pour éviter ce petit override

**Comment by 7studio** [comment]
Pour ceux qui en aurait besoin en attendant une possible intégration, je me suis permis d'extraire le logo ProConnect (à partir de cette source [pc.svg](https://github.com/numerique-gouv/proconnect-documentation/blob/main/assets/pc.svg)) avec quelques ajustements pour respecter le format et le positionnement du logo FranceConnect déjà présent dans le DSFR.

Le fichier SVG (55x48) :

![Image](https://github.com/user-attachments/assets/77fd15f2-dc5d-47a0-bdda-08cd0fea8de9)

Le code CSS : 
```css
.fr-connect--pro {
  padding-left: 4.4375em; // marge intérieure du bouton (0.75em) + largeur de l'icône (3.4375em) + marge entre l'icône et le texte (0.25em)
}

.fr-connect--pro::before {
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='55' height='48' fill='none' viewBox='0 0 55 48'%3E%3Cpath fill='%23000091' d='m34.992 15.0979-14.994-8.677-14.994 8.761a.6061.6061 0 0 0-.306.524v16.948a.6665.6665 0 0 0 .306.524l14.992 8.6 14.994-8.706a.6654.6654 0 0 0 .306-.524v-16.922a.6044.6044 0 0 0-.304-.528Z'/%3E%3Cpath fill='%23FCC63A' d='m14.641 15.5979-5.029 8.628-4.557-9.175 5.39-3.113 4.489 3.16-.293.5Zm20.656 16.98v-16.958a.6004.6004 0 0 0-.306-.523l-14.993-8.676'/%3E%3Cpath fill='%230063CB' d='M4.7 32.5779 20 6.4209v35.362l-14.996-8.605a.6665.6665 0 0 1-.306-.524v-16.948l.002 16.872Zm24.669-20.735 5.458 3.155-4.489 9.15-5.387-9.236 4.418-3.069Z'/%3E%3Cpath fill='%23fff' d='m39.606 12.3029-19.19-11.02a.9328.9328 0 0 0-.832 0L.394 12.303a.887.887 0 0 0-.394.695v22a.8854.8854 0 0 0 .394.7l19.189 11.02a.9325.9325 0 0 0 .832 0l19.191-11.02a.8857.8857 0 0 0 .394-.7v-22a.8868.8868 0 0 0-.394-.695Zm-28.817 17.756h.079c-.042 0-.079.007-.079.05 0 .1.151 0 .2.1a.9123.9123 0 0 0-.629.276c0 .051.1.051.151.051-.075.1-.226.05-.277.151a.1764.1764 0 0 0 .1.05c-.05 0-.1 0-.1.051v.151c-.126 0-.176.1-.277.151.2.151.327 0 .528 0-.528.2-.956.478-1.484.629-.1 0 0 .151-.1.151.151.1.227-.05.377-.05-.654.377-1.333.7-2.037 1.132a.351.351 0 0 0-.1.2h-.2c-.1.05-.05.176-.151.277.226.151.5-.2.654 0 .05 0-.1.05-.2.05-.05 0-.05.1-.1.1H6.99c-.1.075-.2.126-.2.276a.2197.2197 0 0 0-.226.1 9.0314 9.0314 0 0 0 3.144-.578 7.6832 7.6832 0 0 0 2.088-1.559.1764.1764 0 0 1 .05.1 2.1675 2.1675 0 0 1-.806 1.08c-.277.151-.478.377-.7.478a4.0571 4.0571 0 0 0-.428.276 10.7546 10.7546 0 0 1-1.939.412l-.305.044c-.225.033-.449.069-.671.108l-1.993-1.138a.647.647 0 0 1-.288-.411.5693.5693 0 0 0 .094-.063.2658.2658 0 0 0-.113-.071v-.65a12.7815 12.7815 0 0 0 3.038-.942 8.746 8.746 0 0 0-3.037-1.343v-1.515c.5551.091 1.1028.222 1.639.392a6.4205 6.4205 0 0 1 1.182.578c.1466.141.3067.2673.478.377a.9099.9099 0 0 0 .8.05h.33a3.961 3.961 0 0 0 1.937-.905c0 .05.05.05.1.05a3.6287 3.6287 0 0 1-.428 1.132c.003.051-.048.152.053.202Zm2.817 3.571c.251-.1.4-.277.629-.377-.05.05-.05.151-.1.2a3.699 3.699 0 0 0-.528.4 15.965 15.965 0 0 0-1.585 1.61c-.252.3-.528.578-.8.855a2.3842 2.3842 0 0 1-.31.245l-2.527-1.45a4.043 4.043 0 0 0 1.076-.053 4.9823 4.9823 0 0 0 .855-.327v.1c.7-.277 1.232-.906 1.937-1.132.025 0 .126.1.226.05a1.8827 1.8827 0 0 1 1.509-.7c0 .05 0 .1.05.1h.025c-.151.126-.327.251-.5.377-.057.052-.007.102.043.102Zm-8.908-6.164v-.186a5.8169 5.8169 0 0 1 1.588-.188 1.5206 1.5206 0 0 1 .478 0 5.861 5.861 0 0 0-2.066.374Zm30.6 5.088a.6654.6654 0 0 1-.306.524l-10.079 5.851a32.2964 32.2964 0 0 1-3.408-1.185 2.826 2.826 0 0 1-.05-2.245 3.7958 3.7958 0 0 1 .352-.883c.025-.025.05-.05.05-.076a.025.025 0 0 0 .025-.025c.1111-.1945.2371-.38.377-.555l.015-.015.02-.021.015-.015c0-.025.025-.05.05-.076.025-.051.075-.076.1-.126a3.7787 3.7787 0 0 1 .579-.5 4.0871 4.0871 0 0 1 .654-.177c.811.0597 1.6175.1693 2.415.328a.7521.7521 0 0 1 .277.1c.3011.0587.6122.0415.905-.05a1.137 1.137 0 0 0 .855-.706 1.2116 1.2116 0 0 0 .05-1.059c-.178-.276-.013-.437.181-.59l.068-.055a1.1687 1.1687 0 0 0 .231-.216c.126-.252-.1-.4-.151-.63-.05-.1-.226-.05-.327-.2.352-.151.855-.429.629-.857-.151-.227-.377-.63-.1-.857.352-.2.855-.151 1.006-.479a1.1376 1.1376 0 0 0-.292-1.085l-.075-.108c-.075-.107-.149-.214-.211-.32a6.9052 6.9052 0 0 0-.528-.757 4.2972 4.2972 0 0 1-.528-1.009c-.151-.378.05-.706.05-1.084a6.3474 6.3474 0 0 0-.327-2.144c-.126-.353-.176-.731-.327-1.059a1.1201 1.1201 0 0 0-.226-.58.374.374 0 0 1 0-.328 4.8686 4.8686 0 0 0 .579-.479.5674.5674 0 0 0-.2-.706c-.327-.151-.3.328-.528.429h-.151c-.05-.126.05-.177.151-.277 0-.05 0-.151-.05-.151-.2 0-.377-.051-.428-.151a3.9575 3.9575 0 0 0-1.861-1.286c.188.0578.3825.0914.579.1a1.6698 1.6698 0 0 0 1.006-.1c.227-.076.277-.479.377-.706a.8001.8001 0 0 0-.151-.631 2.1902 2.1902 0 0 0-.906-.756c-.176-.076-.453-.227-.679-.353a.9565.9565 0 0 0-.251-.126c-2.965-1.485-9.069-.2-9.534 0h-.009a8.2543 8.2543 0 0 0-1.249.475 3.922 3.922 0 0 0-2.365 2.465 3.8295 3.8295 0 0 0-1.333 1.509c-.428.8-1.056 1.509-.956 2.414.1.78.277 1.484.428 2.289.0429.2721.1099.5398.2.8.1.276 0 .629.151.855.075.151.025.327.227.428v.2c.05.05.05.1.151.1v.2a6.4466 6.4466 0 0 1 1.107 1.434c.1.276-.478.151-.7.05a5.9771 5.9771 0 0 1-1.132-.956.1757.1757 0 0 0-.051.1c.2.352.906.78.528 1.006-.2.1-.428-.151-.629.051-.05.075 0 .176 0 .276-.277-.2-.578-.1-.855-.2-.2-.05-.252-.427-.478-.427a15.191 15.191 0 0 0-1.811-.327 15.1437 15.1437 0 0 0-1.739-.159v-10.969a.6057.6057 0 0 1 .306-.524l14.987-8.761 14.994 8.677a.6054.6054 0 0 1 .306.524v16.932Zm-7.954-8.261a.3247.3247 0 0 1-.282.149 2.8398 2.8398 0 0 0-.282.273c.1 0 0 .149.1.149-.205.223.077.694-.205.793a2.1754 2.1754 0 0 1-1.127 0 .7266.7266 0 0 1 .167-.016h.085a.382.382 0 0 0 .337-.132v-.2c0-.05-.051-.05-.1-.05a.1606.1606 0 0 1-.1.05.2233.2233 0 0 0-.154-.2.8062.8062 0 0 1-.718-.273.6706.6706 0 0 1 .436-.05c.128 0 .077-.223.231-.322h.154c.307-.372.871-.471.974-.843 0-.1-.282-.1-.487-.149a2.2598 2.2598 0 0 0-.82.05 4.6551 4.6551 0 0 0-1.051.273 3.2286 3.2286 0 0 1 .923-.471 3.8871 3.8871 0 0 1 .718-.2l.132-.026.133-.027a.971.971 0 0 1 .556 0c.231.1.615.1.666.248.1.273-.154.545-.435.744-.057.081.149.135.149.23Z'/%3E%3Cpath fill='%23FCC63A' d='M52.56 1H27c-1.1046 0-2 .8954-2 2v9.302c0 1.1046.8954 2 2 2h25.56c1.1046 0 2-.8954 2-2V3c0-1.1046-.8954-2-2-2Z'/%3E%3Cpath fill='%23161616' d='M27.562 12.1676V3.3159h2.921c.9695 0 1.7324.236 2.2888.7081.5648.4721.8473 1.117.8473 1.9348 0 .8093-.2825 1.45-.8473 1.9221-.5564.472-1.3193.7081-2.2888.7081h-1.1254v3.5786H27.562Zm2.9969-7.3216h-1.2013v2.2129h1.2013c.3794 0 .6744-.0969.8852-.2908.2191-.1939.3287-.4721.3287-.8346 0-.3372-.1096-.6028-.3287-.7967-.2108-.1939-.5058-.2908-.8852-.2908ZM35.2306 12.1676V3.3159h2.7061c.9695 0 1.7367.236 2.3015.7081.5648.4721.8472 1.117.8472 1.9348 0 .5311-.1264.9947-.3793 1.391-.2445.3877-.5901.687-1.0369.8978l2.7819 3.92h-2.1497l-2.352-3.5786h-.9231v3.5786h-1.7957Zm2.8073-7.3216h-1.0116v2.2129h1.0116c.3794 0 .6744-.0969.8852-.2908.2107-.1939.3161-.4721.3161-.8346 0-.3372-.1054-.6028-.3161-.7967-.2108-.1939-.5058-.2908-.8852-.2908ZM47.5486 3.063c.6912 0 1.3235.1264 1.8968.3793.5817.253 1.079.5902 1.4921 1.0117.4131.4215.7334.9189.9611 1.4921.2276.5648.3414 1.1634.3414 1.7957 0 .6322-.1138 1.235-.3414 1.8082-.2277.5649-.548 1.058-.9611 1.4795-.4131.4215-.9104.7588-1.4921 1.0117-.5733.2529-1.2056.3793-1.8968.3793-.6913 0-1.3278-.1264-1.9095-.3793-.5817-.2529-1.079-.5902-1.4921-1.0117-.4131-.4215-.7335-.9146-.9611-1.4795-.2276-.5732-.3414-1.176-.3414-1.8082 0-.6323.1138-1.2309.3414-1.7957.2276-.5732.548-1.0706.9611-1.4921.4131-.4215.9104-.7587 1.4921-1.0116.5817-.253 1.2182-.3794 1.9095-.3794Zm0 7.6757c.413 0 .7924-.0759 1.138-.2276.3541-.1602.6534-.3709.8979-.6323.2529-.2698.451-.5859.5943-.9484.1433-.3709.215-.7671.215-1.1886 0-.4216-.0717-.8136-.215-1.1761-.1433-.3709-.3414-.687-.5943-.9484-.2445-.2697-.5438-.4805-.8979-.6322-.3456-.1602-.725-.2403-1.138-.2403-.4131 0-.7967.0801-1.1508.2403-.354.1517-.6575.3625-.9104.6322-.2445.2614-.4384.5775-.5817.9484-.1433.3625-.215.7545-.215 1.1761 0 .4215.0717.8177.215 1.1886.1433.3625.3372.6786.5817.9484.2529.2614.5564.4721.9104.6323.3541.1517.7377.2276 1.1508.2276Z'/%3E%3C/svg%3E");
  background-size: 3.4375em 3em;
  width: 3.4375em;
}
```

Le rendu visuel :

<img alt="Rendu visuel du bouton DSFR avec l'identité ProConnect" src="https://github.com/user-attachments/assets/665e1ff8-73a6-440f-8442-7e17de82cd23" />
