### ISSUE TITLE
Ajuster l'espace entre le texte et le bouton de tri d'une cellule d'en-tête

### ISSUE THREAD

**Issue by goulvench** [GouvernementFR/dsfr#1161]
Dans un tableau, quand une cellule d'en-tête contient un bouton de tri et que le contenu des cellules de données est plus étroit que le texte d'en-tête + le bouton de tri, le bouton se retrouve collé au texte. 

![Image](https://github.com/user-attachments/assets/f58b8a19-8771-4ebd-a7cc-2c9ca13e7cb4)

Il suffit de rajouter une marge à gauche du bouton de tri pour éviter ce problème :

```css
.fr-cell--sort .fr-btn {
  margin-left: .5rem;
}
```

![Image](https://github.com/user-attachments/assets/540d6720-018d-426d-8b6e-012625911387)

**Comment by 7studio** [comment]
Hello @goulvench,

C'est bizarre car dans le code source il y a bien une règle pour ce cas [src/dsfr/component/table/style/module/_default.scss#L129](https://github.com/GouvernementFR/dsfr/blob/edac2ade94251a664badd57d0d50941c6deedb2d/src/dsfr/component/table/style/module/_default.scss#L129) qui génère cette sortie :
```css
.fr-table__content .fr-cell--sort .fr-btn--sort {
  margin-left: 1rem;
}
```
