### ISSUE TITLE
Pagination : augmenter l'espace entre les liens quand il y a la place

### ISSUE THREAD

**Issue by goulvench** [GouvernementFR/dsfr#1162]
La pagination est centrée sur mobile/tablettes/écran zoomé, avec de petites cibles de clic, même quand il y a de la place autour. Exemple dans un tableau : 

![Image](https://github.com/user-attachments/assets/b089ee63-3a7b-4152-83bc-f00ae557c40c)

Il est possible d'augmenter l'espacement pour faciliter le clic sur des cibles petites et proches : 

```css
.fr-pagination {
  width: 100%;
}
.fr-pagination__list {
  align-content: space-between;
  & > li {
    flex-grow: 1;
    display: flex;
    justify-content: center;
  }
}
```

![Image](https://github.com/user-attachments/assets/a5e541a7-81b5-42fa-b544-60b8f60f1ca4)
