### ISSUE TITLE
Classe `fr-btn` non documentée pour usage sur un lien (élément ancre `<a>`)

### ISSUE THREAD

**Issue by loic-brtd** [GouvernementFR/dsfr#1172]
###  Documentation associée
[Composants > Lien - Link](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/lien/)

###  Suggestion
Bonjour, j'ai remarqué que le CSS du DSFR prévoit la possibilité de donner à un lien l'aspect d'un bouton :

```html
<a class="fr-btn" href="...">
```
Extrait du code DSFR :
```css
.fr-btn:disabled,
a.fr-btn:not([href]) {
  --idle: transparent;
  --hover: var(--background-disabled-grey-hover);
  --active: var(--background-disabled-grey-active);
  background-color: var(--background-disabled-grey);
  color: var(--text-disabled-grey)
}
...
.fr-btn[href] {
  text-decoration: none
}
```

J'ai testé et cela fonctionne bien. Cependant, je ne vois pas cette information documentée sur [cette page](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/lien/) : 
- est-ce un oubli ?
- peut-on utiliser ce comportement sans risque qu'il ne soit retiré dans une prochaine version ?
