### ISSUE TITLE
Style des liens un peu aggressif

### ISSUE THREAD

**Issue by thibault** [GouvernementFR/dsfr#264]
Hello,

Lors de mon travail sur [l'application EnvErgo](https://envergo.beta.gouv.fr/), je suis fréquemment confronté à des bugs graphiques provoqués par l'inclusion du dsfr (v1.4.0), notamment à cause du stylage des liens par défaut.

## Exemples de bugs graphiques

Sur des cartes générées par `Leaflet`, les icones d'action sont cassées.

![image](https://user-images.githubusercontent.com/11499/160090898-1285da75-bbd3-403b-9c99-5ff169d248b9.png)

Pour référence, voici le style attendu.

![image](https://user-images.githubusercontent.com/11499/160091053-e37e27c8-227b-4ab1-b43f-f3729ecc25ac.png)

Autre exemple sur le menu fourni par la `django-debug-toolbar` :

![image](https://user-images.githubusercontent.com/11499/160091284-33996a8a-aff4-4f5c-92c1-c0ce275d6dd5.png)

## Origine du problème

J'ai pu tracer l'origine du problème à ce sélecteur présent dans le dsfr :

```css
[href] {
  background-image: var(--underline-img), var(--underline-img);
  background-position: 50% calc(50% + 0.71875em), 50% calc(50% + 0.65625em);
  background-repeat: no-repeat, no-repeat;
  transition: background-size 0s;
  background-size: 0 0.0625em, 100% 0.0625em;
}
```
Le sélecteur me semble un peu radical. On peut imaginer que toutes les applications utilisant un balisage à base de `<a href="#"…` pour représenter quelque chose qui n'est pas strictement un lien classique vont être impactées.

J'ai bien conscience qu'utiliser un tel balisage n'est pas forcément le plus approprié, mais cela reste une pratique très répandue et on n'a pas toujours la main sur le code généré par des applications tierces. Pour ces mêmes raisons, l'utilisation de la classe `.fr-raw-link` n'est pas non-plus forcément une option viable.

## Suggestions

Il peut y avoir de très nombreuses raisons pour lesquelles on trouve des balises `<a>` avec l'attribut `href` renseigné pour représenter des éléments qui ne sont pas des liens. Par conséquent, une règle css qui a un tel impact visuel sur ces éléments devrait peut-être être *opt-in* ? Ou alors, peut-être serait-il envisageable d'utiliser un stylage de liens moins radical ?
