### ISSUE TITLE
Incompatibilité avec postcss-focus-visible

### ISSUE THREAD

**Issue by pcorpet** [GouvernementFR/dsfr#385]
Lorsqu'on utilise ce design system avec le preset par défaut de PostCSS qui inclut notamment [postcss-focus-visible](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-focus-visible), on perd alors l'`outline` correct pour les liens.

À noter que `postcss-focus-visible` est activé par défaut par [postcss-preset-env](https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env) et donc par défaut dans des outils tels que [Nuxt](https://nuxtjs.org).

En effet, le code suivant :
https://github.com/GouvernementFR/dsfr/blob/1511ee98ce0b6c383bf1a9414e1e8f8be3ec3b18/src/core/style/action/module/_focus.scss#L21-L27

est transformé en :
```css
a:focus:not(:focus-visible), button:focus:not(:focus-visible), ... { 
   outline-style: none; 
 } 
a:focus:not(.focus-visible), button:focus:not(.focus-visible), ... { 
   outline-style: none; 
 } 
  
a:focus-visible, button:focus-visible, ... { 
   outline-style: solid; 
 } 
a.focus-visible, button.focus-visible, ... { 
   outline-style: solid; 
 } 
```

La logique du bloc n°2 est alors plus détaillée que la n°3 (elle comprend un pseudo sélecteur + un sélecteur, alors que la n°3 ne comprend qu'un pseudo sélecteur) et prend donc la priorité, à moins qu'un code javascript mette correctement la classe `focus-visible` sur les éléments sélectionnés (ce qui n'est généralement pas le cas).

J'ai mis pas mal de temps à trouver ce bug qui fait qu'un site comme https://incubateur.anct.gouv.fr/ est difficilement navigable au clavier.

Je vois deux solutions possible :
1. documenter quelque part que `dsfr` ne doit pas être utilisé conjointement avec `postcss-focus-visible` à moins d'utiliser également [`focus-visible`](https://github.com/WICG/focus-visible).
2. ajouter un `!important` sur le `outline-style: solid` pour être sûr de gagner la bataille des priorités.
