### ISSUE TITLE
Support RTL 

### ISSUE THREAD

**Issue by sylvainlg** [GouvernementFR/dsfr#495]
Bonjour,

Il y a plusieurs cas de mauvais support des langues RTL.

Jusqu'à présent, j'ai du faire un patch pour :

```css
[dir="rtl"],
[dir="rtl"] .fr-footer__top-cat,
[dir="rtl"] .fr-nav__list > * > .fr-nav__btn,
[dir="rtl"] .fr-nav__list > * > .fr-nav__link,
[dir="rtl"] .fr-nav__list > .fr-nav__btn,
[dir="rtl"] .fr-nav__list > .fr-nav__link,
[dir="rtl"] .fr-nav__btn,
[dir="rtl"] .fr-nav__link {
  text-align: right;
}
```
