### ISSUE TITLE
Le champ "calendrier" a deux icônes

### ISSUE THREAD

**Issue by GllmR** [GouvernementFR/dsfr#530]
Le champ "calendrier" a deux icônes : 

![image](https://user-images.githubusercontent.com/56537238/221134888-e14640a4-b643-49f9-92ad-d9f980ab112d.png)

On peut le constater directement sur le site officiel : 
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/champ-de-saisie

**Comment by keryanS** [comment]
Bonjour,
Une correction a été apporté sur la nouvelle version 1.9

**Comment by GllmR** [comment]
Bonjour @keryanS,

Je viens de mettre à jour le DSFR sur notre projet, et j'ai toujours les deux icônes.
Le problème est également présent dans la documentation : 
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/champ-de-saisie

**Comment by GllmR** [comment]
Le problème est présent uniquement sous Firefox.

Les navigateurs webkit n’ont pas le problème.

**Comment by GllmR** [comment]
Je ne sais pas trop pourquoi cette issue a été fermée.

CF: #411

**Comment by florimondmanca** [comment]
Bonjour,

Après avoir mis à jour vers la 1.10.1, je constate aussi que la double icône est toujours présente sous Firefox

Je dois pour l'instant garder ce correctif:

```css

@supports not selector(::-webkit-calendar-picker-indicator) {
    // Partial FIX for: https://github.com/GouvernementFR/dsfr/issues/530
    // Hide duplicate calendar icon and restore padding when DSFR fails to hide the native calendar icon
    .fr-input-wrap.fr-fi-calendar-line::before {
        display: none;
    }
    .fr-input-wrap .fr-input[type=date] {
        padding-right: 1rem;
    }
}
```
