### ISSUE TITLE
Commentaires superflus dans les fichiers CSS minifiés

### ISSUE THREAD

**Issue by rubycon** [GouvernementFR/dsfr#839]
### Décrire le bug
Les fichiers CSS minifiés contiennent de nombreux commentaires superflus qui impacte leur bonne minification.

### Les étapes pour reproduire le bug
- Installer le projet
- `npm run release`
- Inspecter le fichier `dist/utility/utility.min.css` (ou un autre fichier CSS minifié) :
```css
/*!
 * DSFR v1.10.2 | SPDX-License-Identifier: MIT | License-Filename: LICENSE.md | restricted use (see terms and conditions)
 */.fr-background-default--grey{--idle:transparent;--hover:var( /* ... */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */
  /*! media sm */}@media (min-width:48em){
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */
  /*! media md */}@media (min-width:62em){
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */
  /*! media lg */}@media (min-width:78em){
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */
  /*! media xl */}@media (-ms-high-contrast:active), /* ... */
```
### Comportement attendu
En dehors d'un commentaire de licence en en-tête, un fichier minifié ne devrait pas comporter de commentaires.

### Configuration et système utilisé
- **Version du DSFR :** 1.10.2

### Informations complémentaires
Ces commentaires impactes au final peu la taille des fichiers minifiés (environ 2% de la taille, 7Ko pour `dsfr.min.css`) mais empêche l'optimisation des media query. Le problème se situe dans le module SCSS `shame/media-query` :
```scss
/* ... */ 
@include media-query.respond-from($bp) {
  /*! media #{$bp} */
}
/* ... */ 
```
Le module de minification [CSSNano conserve par défaut](https://cssnano.co/docs/optimisations/discardcomments/) tous les commentaires commençant par `!`.
