### ISSUE TITLE
[Interrupteur] Le libellé est tronqué au milieu du mot

### ISSUE THREAD

**Issue by cstaelen** [GouvernementFR/dsfr#907]
### Décrire le bug
Lorsque l'on utilise un interrupteur avec des libellés checked/unchecked, si le mot est trop long, il est tronqué et le mot s'affiche sur 2 lignes.

### Les étapes pour reproduire le bug
Exemple dans la doc officielle avec le mot "Désactivé" :
https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/interrupteur

### Comportement attendu
Le libellé ne soit pas coupé au milieu d'un mot

### Capture d’écran
<img width="828" alt="Capture d’écran 2024-03-15 à 10 59 22" src="https://github.com/GouvernementFR/dsfr/assets/5319804/aec4561f-b6ae-4987-a93d-c9179fdf0644">

### Configuration et système utilisé
- Version du DSFR : 1.11.1
- Appareil (mobile, tablette, desktop) : *
- Système d’exploitation : *
- Navigateur et version :  constaté sur Firefox 123 & Chromium 122

### Proposition de correctif
```scss
.fr-toggle label[data-fr-unchecked-label][data-fr-checked-label] {
    &::before,
    &::after {
        word-wrap: normal;
    }
}
```
